# Generated by Django 5.1.2 on 2026-04-04 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_cert_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cert',
            name='status',
        ),
    ]
