# Generated by Django 5.1.2 on 2026-04-04 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_cert_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cert',
            options={'ordering': ['issue_date']},
        ),
        migrations.RenameField(
            model_name='cert',
            old_name='expiry_date',
            new_name='issue_date',
        ),
    ]
