# Generated by Django 5.1.2 on 2026-04-06 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_employee_address_line_1_employee_address_line_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_date', models.DateField()),
                ('provider', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_courses', to='accounts.cert')),
            ],
        ),
    ]
