# Generated by Django 5.1.2 on 2026-04-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_bookedcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedcourse',
            name='course_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
