# Generated by Django 5.1.2 on 2026-04-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_changerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedcourse',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Parking, what to bring, instructions etc.'),
        ),
        migrations.AddField(
            model_name='bookedcourse',
            name='booking_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cert',
            name='certificate_number',
            field=models.CharField(blank=True, help_text='Card or cert ref number once issued', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='citb_test_id',
            field=models.CharField(blank=True, help_text='CITB HS&E test ID, required for CSCS renewals', max_length=50),
        ),
    ]
