# Generated by Django 5.1.2 on 2026-04-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_bookedcourse_additional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='plan',
            field=models.CharField(blank=True, choices=[('starter', 'Starter'), ('growth', 'Growth')], max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
