# Generated by Django 5.1.2 on 2026-04-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_company_plan_company_stripe_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='subscription_active',
            field=models.BooleanField(default=True),
        ),
    ]
