# Generated by Django 5.1.2 on 2026-04-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_company_subscription_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='certtype',
            name='booking_instructions',
            field=models.TextField(blank=True, help_text='Internal notes on how to book this cert type — provider, cost, what info is needed etc.'),
        ),
    ]
