# Generated by Django 5.1.2 on 2026-04-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_certtype_booking_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='cert',
            name='extras',
            field=models.JSONField(blank=True, default=dict, help_text='Additional cert-specific fields e.g. card type, occupation, categories'),
        ),
        migrations.AddField(
            model_name='cert',
            name='is_first_application',
            field=models.BooleanField(default=False, help_text="Is this the employee's first ever application for this cert? Affects validity period."),
        ),
        migrations.AddField(
            model_name='certtype',
            name='first_application_days',
            field=models.PositiveIntegerField(blank=True, help_text='Validity in days for first ever application if different from renewal (e.g. CSCS Green Card)', null=True),
        ),
        migrations.AddField(
            model_name='certtype',
            name='renewable',
            field=models.BooleanField(default=True, help_text='Can this cert be renewed or does it require a new application?'),
        ),
        migrations.AddField(
            model_name='certtype',
            name='renewal_window_days',
            field=models.PositiveIntegerField(default=180, help_text='How many days before expiry the renewal window opens'),
        ),
        migrations.AddField(
            model_name='certtype',
            name='required_fields',
            field=models.JSONField(blank=True, default=list, help_text='List of extra fields required to book this cert e.g. ["card_number", "occupation", "card_type"]'),
        ),
        migrations.AddField(
            model_name='company',
            name='billing_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='preferred_providers',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='purchase_order_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='purchase_order_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='cscs_card_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='cscs_card_type',
            field=models.CharField(blank=True, help_text='e.g. Blue Skilled Worker, Green Labourer', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='cscs_occupation',
            field=models.CharField(blank=True, help_text='Occupation as it appears on CSCS card', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='driving_licence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='ipaf_card_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='own_transport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='pasma_card_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='preferred_providers',
            field=models.TextField(blank=True, help_text='Any preferred training providers'),
        ),
        migrations.AddField(
            model_name='employee',
            name='preferred_training_location',
            field=models.CharField(blank=True, help_text='e.g. London, within 20 miles of SW1A 1AA', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Miss', 'Miss'), ('Dr', 'Dr'), ('Prof', 'Prof')], max_length=10),
        ),
        migrations.AlterField(
            model_name='certtype',
            name='renewal_period_days',
            field=models.PositiveIntegerField(help_text='Validity in days for renewal or standard application'),
        ),
    ]
