# Generated by Django 5.1.2 on 2026-04-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_cert_extras_cert_is_first_application_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='preferred_training_location',
        ),
        migrations.AddField(
            model_name='company',
            name='cancel_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cert',
            name='extras',
            field=models.JSONField(blank=True, default=dict, help_text='Additional cert-specific fields e.g. categories, logbook, preferred location'),
        ),
    ]
