# Generated by Django 5.1.2 on 2026-04-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_employee_preferred_training_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='cscs_card_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='cscs_card_type',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='cscs_occupation',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='ipaf_card_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pasma_card_number',
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='preferred_travel_distance',
            field=models.PositiveIntegerField(blank=True, help_text='Max travel distance in miles for training', null=True),
        ),
    ]
