from django.db import migrations


def add_cert_types(apps, schema_editor):
    CertType = apps.get_model('accounts', 'CertType')

    new_certs = [
        {"name": "CITB Health & Safety Test (MAP)", "renewal_period_days": 730,
         "booking_instructions": "Book via CITB website. Valid for 2 years. Required before most CSCS/CPCS/NPORS card applications."},
        {"name": "CPCS Dumper", "renewal_period_days": 1825,
         "booking_instructions": "Book via CPCS accredited test centre. Requires valid CITB MAP test within 2 years."},
        {"name": "CPCS Excavator", "renewal_period_days": 1825,
         "booking_instructions": "Book via CPCS accredited test centre. Requires valid CITB MAP test within 2 years."},
        {"name": "CPCS Crane (Tower)", "renewal_period_days": 1825,
         "booking_instructions": "Book via CPCS accredited test centre. Requires valid CITB MAP test within 2 years."},
        {"name": "CPCS Telehandler", "renewal_period_days": 1825,
         "booking_instructions": "Book via CPCS accredited test centre. Requires valid CITB MAP test within 2 years."},
        {"name": "CPCS Piling", "renewal_period_days": 1825,
         "booking_instructions": "Book via CPCS accredited test centre. Requires valid CITB MAP test within 2 years."},
        {"name": "CPCS Road Roller", "renewal_period_days": 1825,
         "booking_instructions": "Book via CPCS accredited test centre. Requires valid CITB MAP test within 2 years."},
        {"name": "CPCS Slinger/Signaller", "renewal_period_days": 1825,
         "booking_instructions": "Book via CPCS accredited test centre. Requires valid CITB MAP test within 2 years."},
        {"name": "CPCS Appointed Person (Lifting Operations)", "renewal_period_days": 1825,
         "booking_instructions": "Book via CPCS accredited test centre. Requires valid CITB MAP test within 2 years."},
        {"name": "NPORS Trained Operator (Red Card)", "renewal_period_days": 730,
         "booking_instructions": "Book via NPORS accredited test centre. Valid 2 years. Non-renewable — operator must progress to Blue Card via NVQ completion."},
        {"name": "NPORS Competent Operator (Blue Card)", "renewal_period_days": 1825,
         "booking_instructions": "Book via NPORS accredited test centre. Requires valid CITB MAP test within 2 years and relevant NVQ. Renewable every 5 years via renewal form or refresher training."},
        {"name": "NPORS Dumper", "renewal_period_days": 1825,
         "booking_instructions": "Book via NPORS accredited test centre. Requires valid CITB MAP test within 2 years."},
        {"name": "NPORS Excavator", "renewal_period_days": 1825,
         "booking_instructions": "Book via NPORS accredited test centre. Requires valid CITB MAP test within 2 years."},
        {"name": "NPORS Telehandler", "renewal_period_days": 1825,
         "booking_instructions": "Book via NPORS accredited test centre. Requires valid CITB MAP test within 2 years."},
        {"name": "NPORS Forward Tipping Dumper", "renewal_period_days": 1825,
         "booking_instructions": "Book via NPORS accredited test centre. Requires valid CITB MAP test within 2 years."},
        {"name": "NPORS Slinger/Signaller", "renewal_period_days": 1825,
         "booking_instructions": "Book via NPORS accredited test centre. Requires valid CITB MAP test within 2 years."},
        {"name": "Forklift Counterbalance (RTITB)", "renewal_period_days": 1095,
         "booking_instructions": "Book refresher via RTITB accredited provider. Certificate itself does not expire but NORS registration expires every 3 years. HSE recommends refresher every 3 years. Verify NORS number on RTITB website."},
        {"name": "Forklift Reach Truck (RTITB)", "renewal_period_days": 1095,
         "booking_instructions": "Book refresher via RTITB accredited provider. NORS registration expires every 3 years. HSE recommends refresher every 3 years."},
        {"name": "Forklift Rough Terrain (RTITB)", "renewal_period_days": 1095,
         "booking_instructions": "Book refresher via RTITB accredited provider. NORS registration expires every 3 years. HSE recommends refresher every 3 years."},
        {"name": "Forklift Telescopic Handler (RTITB)", "renewal_period_days": 1095,
         "booking_instructions": "Book refresher via RTITB accredited provider. NORS registration expires every 3 years. HSE recommends refresher every 3 years."},
        {"name": "Forklift Counterbalance (ITSSAR)", "renewal_period_days": 1095,
         "booking_instructions": "Book refresher via ITSSAR accredited provider. Certificate does not technically expire but HSE recommends refresher every 3 years. TOPS number on certificate for verification."},
        {"name": "Forklift Reach Truck (ITSSAR)", "renewal_period_days": 1095,
         "booking_instructions": "Book refresher via ITSSAR accredited provider. HSE recommends refresher every 3 years."},
        {"name": "Forklift Rough Terrain (ITSSAR)", "renewal_period_days": 1095,
         "booking_instructions": "Book refresher via ITSSAR accredited provider. HSE recommends refresher every 3 years."},
        {"name": "ECS Electrician (Gold Card)", "renewal_period_days": 1825,
         "booking_instructions": "Renew via JIB at ecscard.org.uk. Requires: valid HSEAP pass (within last 2 years), current 18th Edition (BS7671), passport photo within 6 months, existing card number. Fee approx £36. Processing 10-15 working days."},
        {"name": "ECS Approved Electrician (Gold Card)", "renewal_period_days": 1825,
         "booking_instructions": "Renew via JIB at ecscard.org.uk. Requires: valid HSEAP pass (within last 2 years), current 18th Edition (BS7671), passport photo within 6 months, existing card number. Fee approx £36."},
        {"name": "ECS Engineer (Gold Card)", "renewal_period_days": 1825,
         "booking_instructions": "Renew via JIB at ecscard.org.uk. Requires: valid HSEAP pass (within last 2 years), current qualifications, passport photo within 6 months. Fee approx £36."},
        {"name": "ECS Installer (Gold Card)", "renewal_period_days": 1825,
         "booking_instructions": "Renew via JIB at ecscard.org.uk. Requires: valid HSEAP pass (within last 2 years), current qualifications, passport photo within 6 months. Fee approx £36."},
        {"name": "ECS Trainee", "renewal_period_days": 1095,
         "booking_instructions": "Renew via JIB at ecscard.org.uk. Valid 3 years. Requires valid HSEAP pass within 2 years."},
        {"name": "Gas Safe Registration", "renewal_period_days": 365,
         "booking_instructions": "Renew annually via Gas Safe Register website. Requires valid ACS certificates for applicable appliance categories."},
        {"name": "ACS Natural Gas (CCN1)", "renewal_period_days": 1825,
         "booking_instructions": "Book via ACS approved assessment centre. Requires practical and theory assessment. Valid 5 years."},
        {"name": "ACS LPG (CCN1 LPG)", "renewal_period_days": 1825,
         "booking_instructions": "Book via ACS approved assessment centre. Valid 5 years."},
        {"name": "ACS Cookers (CKR1)", "renewal_period_days": 1825,
         "booking_instructions": "Book via ACS approved assessment centre. Valid 5 years."},
        {"name": "ACS Central Heating (CPA1)", "renewal_period_days": 1825,
         "booking_instructions": "Book via ACS approved assessment centre. Valid 5 years."},
        {"name": "ACS Unvented Hot Water (WAT1)", "renewal_period_days": 1825,
         "booking_instructions": "Book via ACS approved assessment centre. Valid 5 years."},
        {"name": "CISRS Scaffolder Part 1", "renewal_period_days": 1825,
         "booking_instructions": "Book via CISRS approved training provider. Requires CITB MAP test. Valid 5 years."},
        {"name": "CISRS Scaffolder Part 2", "renewal_period_days": 1825,
         "booking_instructions": "Book via CISRS approved training provider. Requires CITB MAP test. Valid 5 years."},
        {"name": "CISRS Advanced Scaffolder", "renewal_period_days": 1825,
         "booking_instructions": "Book via CISRS approved training provider. Requires CITB MAP test. Valid 5 years."},
        {"name": "CISRS Scaffold Inspector", "renewal_period_days": 1825,
         "booking_instructions": "Book via CISRS approved training provider. Valid 5 years."},
        {"name": "CISRS Scaffold Manager", "renewal_period_days": 1825,
         "booking_instructions": "Book via CISRS approved training provider. Valid 5 years."},
        {"name": "Driving Licence (Cat B — Car)", "renewal_period_days": 3650,
         "booking_instructions": "Renew via DVLA. Photo licence renews every 10 years. Medical required at age 70+."},
        {"name": "Driving Licence (Cat C — HGV)", "renewal_period_days": 1825,
         "booking_instructions": "Renew via DVLA. Valid 5 years. Requires medical (D4 form) and CPC qualification."},
        {"name": "Driving Licence (Cat C+E — HGV with Trailer)", "renewal_period_days": 1825,
         "booking_instructions": "Renew via DVLA. Valid 5 years. Requires medical (D4 form) and CPC qualification."},
        {"name": "Driving Licence (Cat D — Bus/Coach)", "renewal_period_days": 1825,
         "booking_instructions": "Renew via DVLA. Valid 5 years. Requires medical (D4 form) and CPC qualification."},
        {"name": "Driving Licence (Cat F — Agricultural)", "renewal_period_days": 3650,
         "booking_instructions": "Renew via DVLA. Photo licence renews every 10 years."},
        {"name": "EUSR Water Hygiene (Blue Card)", "renewal_period_days": 1095,
         "booking_instructions": "Book via EUSR approved trainer. Delivered face-to-face, e-Classroom or e-Learning. 25-question MCQ assessment. Health screening questionnaire required before training. Valid 3 years. Register at eusr.co.uk."},
        {"name": "EUSR NCO Water", "renewal_period_days": 1825,
         "booking_instructions": "Book via EUSR approved provider. Valid 5 years. Renew before expiry to keep EUSR database registration active."},
        {"name": "EUSR SHEA Water", "renewal_period_days": 1095,
         "booking_instructions": "Book via EUSR approved provider. Valid 3 years. Full or half-day renewal routes available depending on current registration status."},
        {"name": "DBS Check (Basic)", "renewal_period_days": 1095,
         "booking_instructions": "Apply via gov.uk or approved umbrella body. No legal expiry but most employers require renewal every 3 years. Cost approx £18."},
        {"name": "DBS Check (Enhanced)", "renewal_period_days": 1095,
         "booking_instructions": "Apply via gov.uk or approved umbrella body. No legal expiry but most employers require renewal every 3 years. Cost approx £38."},
        {"name": "COSHH Awareness", "renewal_period_days": 1095,
         "booking_instructions": "Book via any approved training provider. Valid 3 years. Half or full day course typically."},
        {"name": "Fire Marshal", "renewal_period_days": 1095,
         "booking_instructions": "Book via any approved training provider. Valid 3 years. Half day course typically."},
        {"name": "Mental Health First Aid", "renewal_period_days": 1095,
         "booking_instructions": "Book via MHFA England approved provider. Valid 3 years. Refresher course required at renewal. Certificate issued by Qualsafe, FAIB or MHFA England."},
        {"name": "FGAS Category 1", "renewal_period_days": 1825,
         "booking_instructions": "Mandatory 5-year revalidation. Book via City & Guilds approved assessment centre. Revalidation takes approx 1 day. If lapsed, 12-month grace period applies before full reassessment required. Check status on REFCOM register at refcom.org.uk."},
        {"name": "FGAS Category 2", "renewal_period_days": 1825,
         "booking_instructions": "Mandatory 5-year revalidation. Book via City & Guilds approved assessment centre. If lapsed, 12-month grace period before full reassessment required. Check status on REFCOM register."},
        {"name": "FGAS Category 3", "renewal_period_days": 1825,
         "booking_instructions": "Mandatory 5-year revalidation. Book via City & Guilds approved assessment centre. Check REFCOM register at refcom.org.uk."},
        {"name": "FGAS Category 4", "renewal_period_days": 1825,
         "booking_instructions": "Mandatory 5-year revalidation. Book via City & Guilds approved assessment centre. Check REFCOM register at refcom.org.uk."},
    ]

    for cert in new_certs:
        CertType.objects.get_or_create(
            name=cert["name"],
            defaults={
                "renewal_period_days": cert["renewal_period_days"],
                "booking_instructions": cert.get("booking_instructions", ""),
            }
        )


def remove_cert_types(apps, schema_editor):
    CertType = apps.get_model('accounts', 'CertType')
    names = [
        "CITB Health & Safety Test (MAP)",
        "CPCS Dumper", "CPCS Excavator", "CPCS Crane (Tower)", "CPCS Telehandler",
        "CPCS Piling", "CPCS Road Roller", "CPCS Slinger/Signaller",
        "CPCS Appointed Person (Lifting Operations)",
        "NPORS Trained Operator (Red Card)", "NPORS Competent Operator (Blue Card)",
        "NPORS Dumper", "NPORS Excavator", "NPORS Telehandler",
        "NPORS Forward Tipping Dumper", "NPORS Slinger/Signaller",
        "Forklift Counterbalance (RTITB)", "Forklift Reach Truck (RTITB)",
        "Forklift Rough Terrain (RTITB)", "Forklift Telescopic Handler (RTITB)",
        "Forklift Counterbalance (ITSSAR)", "Forklift Reach Truck (ITSSAR)",
        "Forklift Rough Terrain (ITSSAR)",
        "ECS Electrician (Gold Card)", "ECS Approved Electrician (Gold Card)",
        "ECS Engineer (Gold Card)", "ECS Installer (Gold Card)", "ECS Trainee",
        "Gas Safe Registration", "ACS Natural Gas (CCN1)", "ACS LPG (CCN1 LPG)",
        "ACS Cookers (CKR1)", "ACS Central Heating (CPA1)", "ACS Unvented Hot Water (WAT1)",
        "CISRS Scaffolder Part 1", "CISRS Scaffolder Part 2", "CISRS Advanced Scaffolder",
        "CISRS Scaffold Inspector", "CISRS Scaffold Manager",
        "Driving Licence (Cat B — Car)", "Driving Licence (Cat C — HGV)",
        "Driving Licence (Cat C+E — HGV with Trailer)", "Driving Licence (Cat D — Bus/Coach)",
        "Driving Licence (Cat F — Agricultural)",
        "EUSR Water Hygiene (Blue Card)", "EUSR NCO Water", "EUSR SHEA Water",
        "DBS Check (Basic)", "DBS Check (Enhanced)",
        "COSHH Awareness", "Fire Marshal", "Mental Health First Aid",
        "FGAS Category 1", "FGAS Category 2", "FGAS Category 3", "FGAS Category 4",
    ]
    CertType.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_employee_cscs_card_number_and_more'),
    ]

    operations = [
        migrations.RunPython(add_cert_types, remove_cert_types),
    ]