# Generated by Django 5.1.2 on 2026-05-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_seed_cert_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='plan',
            field=models.CharField(blank=True, choices=[('solo', 'Solo'), ('starter', 'Starter'), ('growth', 'Growth')], max_length=20),
        ),
    ]
