# Generated by Django 5.1.2 on 2025-10-21 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description for SEO')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (60 chars max)', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (160 chars max)', max_length=160)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Post title (appears in H1)', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of title', max_length=200, unique=True)),
                ('excerpt', models.TextField(help_text='Short description (300 chars max) - used in previews and meta description', max_length=300)),
                ('content', models.TextField(help_text='Full blog post content (supports HTML)')),
                ('featured_image', models.ImageField(help_text='Main post image (1200x630px recommended for social sharing)', upload_to='blog/images/%Y/%m/')),
                ('featured_image_alt', models.CharField(blank=True, help_text='Alt text for featured image (important for SEO & accessibility)', max_length=200)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (60 chars max). Leave blank to use post title.', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (160 chars max). Leave blank to use excerpt.', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords (optional, less important nowadays)', max_length=255)),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL (leave blank to use default)')),
                ('og_title', models.CharField(blank=True, help_text='Open Graph title for social sharing (leave blank to use post title)', max_length=100)),
                ('og_description', models.CharField(blank=True, help_text='Open Graph description (leave blank to use excerpt)', max_length=200)),
                ('og_image', models.ImageField(blank=True, help_text='Custom Open Graph image (1200x630px)', upload_to='blog/og_images/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('featured', models.BooleanField(default=False, help_text='Show this post in featured section')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(blank=True, help_text='Schedule publication date', null=True)),
                ('read_time', models.IntegerField(default=5, help_text='Estimated read time in minutes')),
                ('views', models.IntegerField(default=0, help_text='Number of views')),
                ('schema_type', models.CharField(choices=[('Article', 'Article'), ('BlogPosting', 'Blog Posting'), ('NewsArticle', 'News Article'), ('TechArticle', 'Tech Article')], default='Article', max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.tag')),
            ],
            options={
                'ordering': ['-date_published', '-date_created'],
                'indexes': [models.Index(fields=['-date_published'], name='blog_blogpo_date_pu_a5acce_idx'), models.Index(fields=['slug'], name='blog_blogpo_slug_361555_idx'), models.Index(fields=['status'], name='blog_blogpo_status_9c1956_idx')],
            },
        ),
    ]
