# Generated by Django 5.1.2 on 2025-11-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Select multiple tags to categorize this post'),
        ),
    ]
