# Generated by Django 5.1.2 on 2025-11-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogpost_tags_delete_tag_blogpost_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Main post image (1200x630px recommended for social sharing)', null=True, upload_to='blog/images/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Custom Open Graph image (1200x630px)', null=True, upload_to='blog/og_images/'),
        ),
    ]
